/* BV Consulting: interactive SMS AI agent demo (runs fully in the browser, no data is sent anywhere).
   Replies are generated by a lightweight intent engine to show how a med spa AI agent behaves. */
(function () {
  "use strict";

  var SPA = "Your Med Spa";
  var TIMES = ["Tue 11:00 AM", "Wed 4:30 PM", "Thu 1:15 PM", "Sat 10:00 AM"];

  var SERVICES = [
    { key: "neurotoxin", label: "Botox / neurotoxin", phrase: "Botox", re: /\b(botox|dysport|xeomin|daxxify|jeuveau|neurotoxin|tox|wrinkle|forehead|crow'?s? ?feet|frown|11s|elevens)\b/i,
      info: "Neurotoxin treatments like Botox soften expression lines on areas such as the forehead, frown lines, and crow's feet. Appointments are usually quick, and a licensed provider maps out your plan at a free consultation." },
    { key: "filler", label: "Dermal filler", phrase: "filler", re: /\b(filler|fillers|lip|lips|cheek|cheeks|jaw|jawline|chin|juvederm|restylane|rha|volume)\b/i,
      info: "Dermal filler can add volume and definition to areas like the lips, cheeks, and jawline. Your provider will talk through the look you want and how many syringes make sense at a free consultation." },
    { key: "laser", label: "Laser hair removal", phrase: "laser hair removal", re: /\b(laser|hair removal|ipl|remove hair|bikini|underarm)\b/i,
      info: "Laser hair removal works over a series of sessions spaced a few weeks apart. We'll do a quick skin consult first to choose the right settings for you." },
    { key: "skin", label: "Facials & skin", phrase: "skin treatment", re: /\b(facial|facials|hydrafacial|peel|peels|microneedling|skin|acne|glow|dark spots|texture|rf)\b/i,
      info: "We offer facials, chemical peels, and microneedling for glow, texture, and tone. An aesthetician can recommend the best fit after a quick skin assessment." },
    { key: "weight", label: "Medical weight loss", phrase: "weight loss", re: /\b(weight loss|weight|semaglutide|tirzepatide|glp|ozempic|wegovy)\b/i,
      info: "We offer medically supervised weight loss programs. Eligibility is determined by a licensed provider during a consultation." }
  ];

  var RULES = [
    { id: "stop", re: /^\s*(stop|unsubscribe|cancel texts|opt ?out)\s*$/i },
    { id: "urgent", re: /\b(emergency|can'?t breathe|trouble breathing|severe|allergic reaction|911|vision|blister|infection|infected|pus|fever)\b/i },
    { id: "medical", re: /\b(swelling|swollen|bruis\w*|lump|reaction|side effects?|pregnan\w*|breastfeed\w*|nursing|medication|blood thinner|safe for me)\b/i },
    { id: "comfort", re: /\b(hurt|hurts|painful|pain|numb\w*|needle|needles)\b/i },
    { id: "human", re: /\b(human|real person|person|someone|staff|call me|speak to|talk to|representative|manager)\b/i },
    { id: "confirm", re: /^\s*(c|confirm|confirmed)\s*$/i },
    { id: "resched", re: /^\s*r\s*$|\b(reschedul\w*|move my|change my|cancel my|different time)\b/i },
    { id: "hours", re: /\b(hours|open|close|closing|weekend|saturday|sunday|location|address|where are you|located|parking|park)\b/i },
    { id: "price", re: /\b(price|prices|pricing|cost|costs|how much|\$|per unit|per syringe|expensive|afford|financ\w*)\b/i },
    { id: "member", re: /\b(membership|member|package|packages|special|specials|deal|deals|promo|promotion|discount|offer)\b/i },
    { id: "deposit", re: /\b(deposit|cancellation|no[- ]show|late policy|policy)\b/i },
    { id: "downtime", re: /\b(downtime|recovery|how long|last|results|before and after|prep|prepare)\b/i },
    { id: "book", re: /\b(book\w*|appointments?|appts?|schedul\w*|available|availability|openings?|consult\w*|come in|sign me up)\b/i },
    { id: "no", re: /^\s*(no|nope|not now|not right now|maybe later|later|no thanks)\b/i },
    { id: "yes", re: /^\s*(yes|yeah|yep|sure|ok|okay|sounds good|please|let'?s do it|book me)\b/i },
    { id: "thanks", re: /\b(thanks|thank you|thx|ty|appreciate)\b/i },
    { id: "hi", re: /^\s*(hi|hello|hey|hiya|good (morning|afternoon|evening))\b/i }
  ];

  var SCENARIOS = {
    lead: {
      start: [{ ai: "Hi! Thanks for texting " + SPA + ". I'm the virtual assistant and I can help with pricing, treatments, and booking. What can I help you with today?" }],
      chips: ["How much is lip filler?", "Book a consultation", "Do you do laser hair removal?", "What are your hours?"]
    },
    missed: {
      start: [{ sys: "Missed call from (555) 010-2233 · 7:48 PM" },
              { ai: "Hi, this is " + SPA + "! Sorry we missed your call. We're with clients right now, but I can help by text. What were you calling about?" }],
      chips: ["I want to book Botox", "Pricing question", "Talk to a person"]
    },
    reminder: {
      start: [{ ai: "Hi Jess! Reminder: your appointment at " + SPA + " is tomorrow at 2:30 PM.\nReply C to confirm or R to reschedule." }],
      chips: ["C", "R", "Where do I park?"],
      ctx: { name: "Jess", appt: true }
    },
    rebook: {
      start: [{ ai: "Hi Jess! It's been about 3 months since your last neurotoxin visit, which is when many clients plan their next one. Want me to find a time that works for you?" }],
      chips: ["Yes, book me", "Any specials right now?", "Not right now"],
      ctx: { name: "Jess", service: "neurotoxin" }
    }
  };

  function icon(path, size) {
    return '<svg width="' + (size || 14) + '" height="' + (size || 14) + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + path + '</svg>';
  }

  function Demo(root) {
    this.root = root;
    this.chat = root.querySelector(".chat");
    this.chipsEl = root.querySelector(".chips");
    this.form = root.querySelector(".phone-input");
    this.input = this.form.querySelector("input");
    this.sendBtn = this.form.querySelector("button");
    this.busy = false;
    this.timers = [];
    var self = this;
    this.form.addEventListener("submit", function (e) {
      e.preventDefault();
      var t = self.input.value.trim();
      if (!t || self.busy) return;
      self.input.value = "";
      self.user(t);
    });
    var tabs = document.querySelectorAll('[data-demo-tab="' + root.id + '"]');
    this.tabs = tabs;
    tabs.forEach(function (tab) {
      tab.addEventListener("click", function () { self.load(tab.getAttribute("data-scenario")); });
    });
    var reset = root.querySelector(".phone-reset");
    if (reset) reset.addEventListener("click", function () { self.load(self.scenario); });
    this.load(root.getAttribute("data-start") || "lead");
  }

  Demo.prototype.clearTimers = function () { this.timers.forEach(clearTimeout); this.timers = []; };

  Demo.prototype.load = function (name) {
    var sc = SCENARIOS[name] || SCENARIOS.lead;
    this.clearTimers();
    this.scenario = name;
    this.ctx = Object.assign({ stage: null, service: null, name: null, appt: false }, sc.ctx || {});
    this.chat.innerHTML = "";
    this.setChips([]);
    this.tabs.forEach(function (t) { t.setAttribute("aria-pressed", t.getAttribute("data-scenario") === name ? "true" : "false"); });
    var self = this, delay = 250;
    sc.start.forEach(function (m) {
      if (m.sys) { self.timers.push(setTimeout(function () { self.sys(m.sys); }, delay)); delay += 450; }
      if (m.ai) { self.aiReply([m.ai], null, delay); delay += Math.min(1500, 550 + m.ai.length * 9) + 500; }
    });
    this.timers.push(setTimeout(function () { self.setChips(sc.chips); }, delay));
    if (window.BV && window.BV.track && this.loaded) window.BV.track("sms_demo_scenario", { scenario: name });
    this.loaded = true;
  };

  Demo.prototype.scroll = function () { this.chat.scrollTop = this.chat.scrollHeight; };

  Demo.prototype.add = function (cls, text) {
    var el = document.createElement("div");
    el.className = cls;
    el.textContent = text;
    this.chat.appendChild(el);
    this.scroll();
    return el;
  };

  Demo.prototype.sys = function (text) {
    var el = document.createElement("div");
    el.className = "msg-sys";
    el.innerHTML = icon('<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/>', 12);
    el.appendChild(document.createTextNode(text));
    this.chat.appendChild(el);
    this.scroll();
  };

  Demo.prototype.card = function (title, body, ok) {
    var el = document.createElement("div");
    el.className = "msg-card" + (ok ? " ok" : "");
    var b = document.createElement("b"); b.textContent = title;
    el.appendChild(b); el.appendChild(document.createTextNode(body));
    this.chat.appendChild(el);
    this.scroll();
  };

  Demo.prototype.setChips = function (list) {
    var self = this;
    this.chipsEl.innerHTML = "";
    (list || []).forEach(function (c) {
      var b = document.createElement("button");
      b.type = "button"; b.className = "chip"; b.textContent = c;
      b.addEventListener("click", function () { if (!self.busy) self.user(c); });
      self.chipsEl.appendChild(b);
    });
    this.chipsEl.hidden = !list || !list.length;
  };

  Demo.prototype.aiReply = function (texts, after, startDelay) {
    var self = this;
    var delay = startDelay || 350;
    this.busy = true; this.sendBtn.disabled = true;
    texts.forEach(function (t, i) {
      var typingEl;
      self.timers.push(setTimeout(function () {
        typingEl = document.createElement("div");
        typingEl.className = "typing"; typingEl.setAttribute("aria-label", "Assistant is typing");
        typingEl.innerHTML = "<span></span><span></span><span></span>";
        self.chat.appendChild(typingEl); self.scroll();
      }, delay));
      var dur = Math.min(1500, 550 + t.length * 9);
      delay += dur;
      self.timers.push(setTimeout(function () {
        if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);
        self.add("msg ai", t);
        if (i === texts.length - 1) {
          self.busy = false; self.sendBtn.disabled = false;
          if (after) after();
        }
      }, delay));
      delay += 250;
    });
  };

  Demo.prototype.user = function (text) {
    this.setChips([]);
    this.add("msg me", text);
    if (window.BV && window.BV.track) window.BV.track("sms_demo_message");
    var r = this.respond(text);
    var self = this;
    this.aiReply(r.texts, function () {
      if (r.card) self.card(r.card[0], r.card[1], r.card[2]);
      self.setChips(r.chips || []);
    });
  };

  function findService(text) {
    for (var i = 0; i < SERVICES.length; i++) { if (SERVICES[i].re.test(text)) return SERVICES[i]; }
    return null;
  }
  function svcByKey(k) { for (var i = 0; i < SERVICES.length; i++) { if (SERVICES[i].key === k) return SERVICES[i]; } return null; }
  function matchTime(text) {
    var t = text.toLowerCase();
    for (var i = 0; i < TIMES.length; i++) { if (t === TIMES[i].toLowerCase()) return TIMES[i]; }
    var day = t.match(/\b(mon|tue|wed|thu|fri|sat|sun)[a-z]*\b|\b(today|tomorrow)\b/);
    var hour = t.match(/\b(\d{1,2})(:\d{2})?\s*(am|pm)\b|\b(morning|afternoon|evening|noon)\b/);
    if (day || hour) {
      var d = day ? (day[0].charAt(0).toUpperCase() + day[0].slice(1)) : "Wed";
      var h = hour ? hour[0].replace(/\s+/g, " ").toUpperCase().replace("MORNING", "10:00 AM").replace("AFTERNOON", "2:00 PM").replace("EVENING", "5:30 PM").replace("NOON", "12:00 PM") : "4:30 PM";
      if (/^\d{1,2}\s?(AM|PM)$/.test(h)) h = h.replace(/\s?(AM|PM)/, ":00 $1");
      return d + " " + h;
    }
    return null;
  }

  Demo.prototype.respond = function (text) {
    var ctx = this.ctx;
    var svc = findService(text);
    if (svc) ctx.service = svc.key;
    var intent = null;
    for (var i = 0; i < RULES.length; i++) { if (RULES[i].re.test(text)) { intent = RULES[i].id; break; } }

    if (ctx.stage === "callback" && (intent === "yes" || /\bnumber\b/i.test(text))) {
      ctx.stage = null;
      return { texts: ["Perfect, we'll reach you at this number. Talk soon!"], chips: ["Thanks!"] };
    }
    // Mid-booking: user picks a time
    if (ctx.stage === "time") {
      var slot = matchTime(text);
      if (slot) {
        ctx.stage = "booked";
        var s = svcByKey(ctx.service);
        if (ctx.appt) {
          return { texts: ["Done! Your appointment is moved to " + slot + ". I'll send a reminder the day before."],
                   card: ["✓ Appointment rescheduled", slot + "\nUpdated in booking software (demo)", true], chips: ["Where do I park?", "Thanks!"] };
        }
        return { texts: ["You're all set! 🎉 I booked your " + (s ? s.phrase + " " : "") + "consultation for " + slot + ".", "You'll get a reminder text the day before. Reply R anytime to reschedule."],
                 card: ["✓ Appointment booked", (s ? s.label + " consult" : "Consultation") + " · " + slot + "\nSynced to calendar & CRM (demo)", true],
                 chips: ["Where do I park?", "What should I do to prepare?", "Thanks!"] };
      }
    }
    // Choosing a service during booking
    if (ctx.stage === "service" && svc) {
      ctx.stage = "time";
      return { texts: ["Perfect, a " + svc.phrase + " consultation. Here are the next openings I have:"], chips: TIMES };
    }

    switch (intent) {
      case "stop":
        ctx.stage = null;
        return { texts: ["You've been unsubscribed from " + SPA + " texts and won't receive more messages. Reply START to opt back in."], chips: [] };
      case "urgent":
        ctx.stage = null;
        return { texts: ["I'm sorry you're dealing with that. If this is a medical emergency, please call 911 right away.", "I've also alerted our licensed provider on call so they can reach out to you as quickly as possible."],
                 card: ["⚑ Escalated to provider", "Urgent message flagged for clinical team (demo)"], chips: ["Talk to a person"] };
      case "medical":
        return { texts: ["That's an important question, and it's best answered by one of our licensed providers rather than me.", "I've sent your message to our nurse team and someone will follow up shortly. If it's urgent, please call us or 911."],
                 card: ["⚑ Routed to clinical team", "Medical question handed off to a licensed provider (demo)"], chips: ["Book a consultation", "Talk to a person"] };
      case "human":
        ctx.stage = "callback";
        return { texts: ["Of course! I've let our front desk know you'd like to talk with a person. Someone will call or text you back during business hours.", "Is this the best number to reach you?"],
                 card: ["☎ Callback requested", "Task created for front desk in CRM (demo)"], chips: ["Yes, this number", "Thanks!"] };
      case "confirm":
        if (ctx.appt || ctx.stage === "booked") {
          return { texts: ["Thanks" + (ctx.name ? ", " + ctx.name : "") + "! Your appointment is confirmed. See you soon! 💚"], card: ["✓ Confirmed", "Status updated in booking software (demo)", true], chips: ["Where do I park?", "What should I do to prepare?"] };
        }
        break;
      case "resched":
        ctx.stage = "time";
        return { texts: ["No problem, let's find a better time. Here are the next available openings:"], chips: TIMES };
      case "hours":
        if (/park/i.test(text)) return { texts: ["There's free parking in the lot right behind our building, and the entrance is on the left. (Your real parking details go here.)"], chips: ["What are your hours?", "Book a consultation"] };
        return { texts: ["We're open Monday to Friday 9 AM to 7 PM and Saturday 9 AM to 3 PM. (Demo hours: your agent uses your real schedule and address.)"], chips: ["Book a consultation", "Where do I park?"] };
      case "price":
        var ps = svcByKey(ctx.service);
        var detail = ps && ps.key === "neurotoxin" ? "Neurotoxin is typically priced per unit, and the number of units depends on the areas you treat." :
                     ps && ps.key === "filler" ? "Filler is typically priced per syringe, and most plans depend on the area and the look you want." :
                     ps && ps.key === "laser" ? "Laser hair removal is priced by treatment area, and packages of sessions usually lower the per-visit cost." :
                     "Pricing depends on the treatment and your personal plan.";
        ctx.stage = "offer";
        return { texts: [detail, "Your consultation is free, and your provider will give you an exact quote. Want me to find a time for you?"], chips: ["Yes, book me", "Any specials right now?", "Not right now"] };
      case "member":
        return { texts: ["We have a monthly membership with perks like member pricing and a complimentary facial each month, plus seasonal specials. (Your agent shares your real offers.)", "Want me to book a consultation so we can recommend the best option?"], chips: ["Yes, book me", "Not right now"] };
      case "deposit":
        return { texts: ["To hold longer appointments we ask for a small deposit that goes toward your treatment. Please give us 24 hours notice to reschedule so we can offer the spot to someone on our waitlist."], chips: ["Book a consultation", "Thanks!"] };
      case "downtime":
        var ds = svcByKey(ctx.service);
        return { texts: [(ds ? ds.info + " " : "") + "Downtime and results vary by treatment and by person, so your provider will go over exactly what to expect and how to prepare before your visit."], chips: ["Book a consultation", "How much does it cost?"] };
      case "comfort":
        return { texts: ["Comfort is a top priority. Many treatments can include numbing or cooling options, and your provider will talk you through exactly what to expect."], chips: ["Book a consultation", "Is there downtime?"] };
      case "book":
      case "yes":
        if (intent === "yes" && ctx.stage === "booked") return { texts: ["You're already booked! Anything else I can help with?"], chips: ["Where do I park?", "Thanks!"] };
        if (ctx.service) {
          ctx.stage = "time";
          return { texts: ["I'd love to get you booked! Here are the next available openings for a " + svcByKey(ctx.service).phrase + " consultation:"], chips: TIMES };
        }
        ctx.stage = "service";
        return { texts: ["I'd love to get you booked! Which treatment are you interested in?"], chips: SERVICES.map(function (s) { return s.label; }) };
      case "no":
        ctx.stage = null;
        return { texts: ["No problem at all! I'll check back in a few weeks. You can text us anytime, and reply STOP to opt out of messages."], chips: [] };
      case "thanks":
        return { texts: ["You're so welcome! Text anytime if you have more questions. 😊"], chips: ["Book a consultation"] };
      case "hi":
        return { texts: ["Hi there! I can help with treatment questions, pricing, and booking. What are you interested in?"], chips: ["Botox", "Lip filler", "Laser hair removal", "Facials"] };
    }

    if (svc) {
      ctx.stage = "offer";
      return { texts: [svc.info, "Would you like me to book a free consultation?"], chips: ["Yes, book me", "How much does it cost?", "Is there downtime?"] };
    }
    if (ctx.stage === "time") {
      return { texts: ["Which of these times works best for you? You can also tell me a day and time, like \"Friday at 3 PM\"."], chips: TIMES };
    }
    return { texts: ["Great question! I'll pass that to our team so they can give you the right answer.", "In the meantime, I can help with treatments, pricing, or booking a consultation."],
             chips: ["Book a consultation", "Pricing", "Talk to a person"] };
  };

  function init() {
    document.querySelectorAll("[data-sms-demo]").forEach(function (el) { if (!el._demo) el._demo = new Demo(el); });
    if ("IntersectionObserver" in window) {
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (en) { document.body.classList.toggle("demo-in-view", en.isIntersecting); });
      }, { threshold: 0.15 });
      document.querySelectorAll("[data-sms-demo]").forEach(function (el) { io.observe(el); });
    }
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
